require 'app/jobs/merge_job'
require 'app/jobs/accept_submission_job'
require 'app/jobs/deploy_viewer_sinatra_pull_request_job'
require 'app/jobs/handle_everypolitician_data_pull_request_job'
require 'app/jobs/send_webhook_job'
